ITEM.name = "FAMAS"
ITEM.description = "A 5.56x45mm bullpuped carbine popular in european law enforcement and military applications."
ITEM.category = "Weapons - Guns"
ITEM.model = "models/weapons/tfa_flf/p_famas.mdl"
ITEM.class = "tfa_flf_famas"
ITEM.width = 3
ITEM.height = 2
ITEM.isWeapon = true
ITEM.isGrenade = false
ITEM.weaponCategory = "main"
ITEM.useSound = "items/ammo_pickup.wav"
ITEM.rarity = "Uncommon"
ITEM.price = 1150