ITEM.name = "M3 Grease Gun"
ITEM.description = "A submachine gun remenicient of old movies."
ITEM.category = "Weapons - Guns"
ITEM.model = "models/weapons/svencoop/th/w_greasegun.mdl"
ITEM.class = "tfa_svencoop_theyhunger_greasegun"
ITEM.width = 3
ITEM.height = 2
ITEM.isWeapon = true
ITEM.isGrenade = false
ITEM.weaponCategory = "main"
ITEM.useSound = "items/ammo_pickup.wav"
ITEM.rarity = "Uncommon"
ITEM.price = 400