ITEM.name = "Hatchet"
ITEM.description = "A simple steel axe. Slightly rusted and worn with time."
ITEM.category = "Weapons - Melee"
ITEM.model = "models/weapons/tfa_nmrih/w_me_hatchet.mdl"
ITEM.class = "tfa_nmrih_hatchet"
ITEM.width = 1
ITEM.height = 2
ITEM.isWeapon = true
ITEM.isGrenade = false
ITEM.weaponCategory = "melle"
ITEM.useSound = "player/shove_01.wav"
ITEM.rarity = "Common"
ITEM.price = 250