ITEM.name = "Umbrella"
ITEM.description = "A boring, plain umbrella."
ITEM.category = "Weapons - Melee"
ITEM.model = "models/weapons/svencoop/th/w_umbrella.mdl"
ITEM.class = "tfa_svencoop_th_umbrella"
ITEM.width = 1
ITEM.height = 2
ITEM.isWeapon = true
ITEM.isGrenade = false
ITEM.weaponCategory = "melle"
ITEM.useSound = "items/ammo_pickup.wav"
ITEM.rarity = "Common"
ITEM.price = 350